events {}

http {
    upstream backend_servers {
        server lb_backend1:80;
        server lb_backend2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
