FROM alpine:latest as builder

RUN apk add --no-cache curl

RUN curl -L -o coredns.tgz https://github.com/coredns/coredns/releases/download/v1.12.1/coredns_1.12.1_linux_amd64.tgz
RUN tar xvf coredns.tgz

FROM alpine:latest

RUN apk add --no-cache libc6-compat tcpdump

WORKDIR /coredns

COPY --from=builder coredns .

RUN chmod +x ./coredns
RUN mv coredns /usr/local/bin/

COPY Corefile .

EXPOSE 53/udp
EXPOSE 53/tcp

CMD coredns -conf ./Corefile
