name: 'mininet_vnf'

services:
    vnf_nat:
        image: vnf_nat:0.0.3
        container_name: vnf_nat
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
            - NET_RAW
        environment:
            - NAT_INTF=eth0
    vnf_dns:
        image: vnf_dns:0.0.1
        build:
            context: ./dns
            dockerfile: Dockerfile.DNS
        container_name: vnf_dns
        cap_add:
            - NET_ADMIN
        volumes:
            - ./dns/Corefile:/etc/coredns/Corefile
    vnf_fw:
        image: vnf_firewall:0.0.1
        container_name: vnf_firewall
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
            - NET_RAW
    vnf_frr:
        image: vnf_frr:0.0.1
        container_name: vnf_frr
        build:
            context: ./frr
            dockerfile: Dockerfile.FRR
        volumes:
            - ./frr/frr.conf:/etc/frr/frr.conf:ro
            - ./frr/daemons:/etc/frr/daemons:ro
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
            - NET_RAW
    vnf_tc:
        image: vnf_tc:0.0.2
        container_name: vnf_tc
        build:
            context: ./tc
            dockerfile: Dockerfile.TC
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
            - NET_RAW
    vnf_lb:
        image: vnf_lb:0.0.1
        container_name: vnf_lb
        build:
            context: ./lb
            dockerfile: Dockerfile.LB
        stdin_open: true
        tty: true
    lb_backend1:
        image: nginx:stable-alpine
        container_name: lb_backend1
        hostname: lb_backend1
    lb_backend2:
        image: nginx:stable-alpine
        container_name: lb_backend2
        hostname: lb_backend2
